names = {
"Australia" : ["Olivia", "Charlotte", "Emily", "Chloe", "Ella", "Jessica", "Isabella", "Sophie", "Mia", "Emma"],
"Belgium" : ["Emma", "Marie", "Laura", "Julie", "Sarah", "Clara", "Manon", "Léa", "Lisa", "Camille"],
"Denmark" : ["Mathilde", "Emma", "Laura", "Sofie", "Freja", "Caroline", "Ida", "Sara", "Julie", "Anna"],
"France" : ["Léa", "Manon", "Emma", "Chloé", "Camille", "Océane", "Clara", "Marie", "Sarah", "Inès"],
"Hungary" : ["Anna", "Viktória", "Réka", "Vivien", "Zsófia", "Petra", "Dorina", "Fanni", "Boglárka", "Eszter"],
"Norway" : ["Emma", "Thea", "Ida", "Sara", "Julie", "Emilie", "Hanna", "Nora", "Malin", "Ingrid"],
"Portugal" : ["Maria", "Joana", "Ana", "Catarina", "Inês", "Teresa", "Isabel", "Margarida", "Carolina", "Filipa"],
"Spain" : ["Lucía", "Sofia", "Martina", "Maria", "Paula", "Julia", "Emma", "Valeria", "Daniela", "Alba"],
"Sweden" : ["Emma", "Maja", "Julia", "Alice", "Ida", "Linnéa", "Elin", "Alva", "Hanna", "Ella"],
"United States" : ["Emily", "Emma", "Madison", "Abigail", "Olivia", "Isabella", "Hannah", "Samantha", "Ava", "Ashley"],